### PR TITLE
Follow Avalonia startup sequence + experiment with single project format

### PR DESCRIPTION
**Pull request by TimLariviere**
The official Avalonia crossplatform F# templates use a shared F# library with several heads for each platform (`iOS`, `Android`, `Desktop`, `Web`, etc).

Based on my previous experience working on the F# MAUI template, I feel like we can achieve the same single project solution for Avalonia, just by making use of multitargeting with `net7.0-ios`, `net7.0-android`, etc.

This PR includes for now the single project format for both iOS and Desktop:

image

### CODE REVIEW

**Comment by TimLariviere** [comment]
Note that this PR relies on some changes inside Fabulous that are not committed yet

**Comment by edgarfgp** [comment]
This is looking good :)

**Comment by TimLariviere** [comment]
image

**Comment by TimLariviere** [comment]
@edgarfgp This PR now supports iOS, Android and Desktop into a single project :)
single-project-results

**Comment by edgarfgp** [comment]
> @edgarfgp This PR now supports iOS, Android and Desktop into a single project :)

Ship it 🚀 😀

**Pull request merged**
